# Generated by Django 2.2.12 on 2020-05-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRegisters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('details', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='registers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.GroupRegisters'),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.Student'),
        ),
    ]
