# Generated by Django 2.2.12 on 2020-05-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serv', '0002_auto_20200508_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentslist',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.StudentsList'),
        ),
    ]
