# Generated by Django 2.2.12 on 2020-05-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv', '0004_studentslist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
