# Generated by Django 2.2.12 on 2020-05-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serv', '0005_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='registers',
        ),
        migrations.AddField(
            model_name='groupregisters',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.Group'),
        ),
    ]
