# Generated by Django 2.2.12 on 2020-05-08 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serv', '0006_auto_20200508_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.Teacher'),
        ),
        migrations.AddField(
            model_name='groupregisters',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.Teacher'),
        ),
    ]
