# Generated by Django 2.2.12 on 2020-05-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serv', '0007_auto_20200508_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serv.StudentsList'),
        ),
    ]
