# Generated by Django 2.2.12 on 2020-05-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serv', '0008_auto_20200509_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.Group'),
        ),
        migrations.DeleteModel(
            name='StudentsList',
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serv.Group'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Serv.Teacher'),
        ),
    ]
